Laravel 5 rewrite and test addition
Braunson/fatsecret-laravel pull request #9
Opened 2017-12-22 23:54 UTC by namelivia

I got this ready, it comes with a lot of chages so it should be carefully checked.
This is a summary of what I've done:
- StyleCI added for code style checking and adapted the code for it.
- Unit and integration tests for almost everything, executed through phpunit and TravisCI.
- The code has been reorganized for better testeability and (hopefully) readability and extendability. This means for example that adding new api methods should easy by adding short functions for them to `FatSecret.php`.
- API error handling by throwing custom Exceptions
- Complete integration test by calling all the methods from an example laravel 5 app to check they work.
Feel free to comment and criticize everything you don't like

2018-07-05 18:35 UTC, Braunson requested changes

2018-07-05 18:35 UTC, Braunson commented on README.md
> +[![Build Status](https://travis-ci.org/namelivia/fatsecret-laravel.svg?branch=laravel5)](https://travis-ci.org/namelivia/fatsecret-laravel)
These badges are not for this repository

2018-07-05 18:35 UTC, Braunson commented on README.md
> +			'secret' => 'YOUR-API-SECRET'
These should support being set via environmental variables in the `.env` file.

2019-12-11 08:27 UTC, closed without merging

2019-12-11 18:49 UTC, Braunson commented
@namelivia Is this still available, I totally forgot about this PR and wanted to test it to have it merged as V2!

2019-12-18 23:06 UTC, Braunson commented
@namelivia Following up once more, are you able to add this PR back, I'd like to merge it in after a quick test?

2019-12-19 09:22 UTC, namelivia commented
This PR can't be reopened. However, next week I'll have some spare time so I can take a look at it and come up with something.

2019-12-22 15:33 UTC, namelivia commented
I recreated the changes on #10 , I've checked that the unit tests are passing but haven't fully tested it with the actual API (I did that when I opened the last PR so I assume it will still work).

2019-12-22 18:30 UTC, Braunson commented
@namelivia Thank you so much. I just made some minor adjustments, going to test with live credentials now on 5.2 then will make a release for 5.x and then another for 6.x.

I'm curious what version of Laravel are you running this package on?

2019-12-22 19:22 UTC, namelivia commented
There are some versioning issues, some Laravel versions require some phpunit, mockery and php versions that will require some minor changes on each versions of the code. That's why the build is failing, I'm currently setting those up, we can continue the discussion in the currently open PR.